codecov:
  max_report_age: off

coverage:
  status:
    project:
      default:
        target: auto
        range: 60..90
        round: down
        precision: 2
        threshold: 5%
        base: auto

comment: off
